---
- name: Configure DNF package manager.
  template:
    src: templates/dnf.conf.j2
    dest: /etc/dnf/dnf.conf
    mode: 0644

- name: Update system.
  import_role:
    name: dnfupdate

- name: Basic security configuration.
  import_role:
    name: geerlingguy.security

- name: Install EPEL repository.
  package:
    name: epel-release
    state: present
